-- ============================================================================
-- Digos City Government - Employee Payroll Management System
--
-- THIS FILE NO LONGER CONTAINS THE SCHEMA.
--
-- The schema is now a sequence of numbered migrations under migrations/,
-- applied by the migration runner:
--
--     php tools/migrate.php            apply every pending migration
--     php tools/migrate.php --status   show applied / pending
--     php tools/migrate.php --dry-run  show what would run, change nothing
--
-- The runner creates the database if it does not exist, so a fresh install
-- needs only that one command - no `mysql -u root -p < schema.sql` step.
-- Connection settings come from app/config.php, or from the DB_HOST, DB_NAME,
-- DB_USER and DB_PASS environment variables when those are set.
--
-- WHY THE CHANGE
-- A single CREATE-TABLE-IF-NOT-EXISTS file cannot express a change to an
-- existing table, so every schema change after the first release had nowhere
-- to live. It also drifts from the real database with no way to detect that
-- it has. Migrations are ordered, applied exactly once, recorded in the
-- schema_migrations table, and checksum-verified against what was applied.
--
-- The original contents of this file are preserved verbatim as
-- migrations/0001_baseline_schema.sql.
-- ============================================================================
